# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

openmp_installed <- function() {
    .Call(`_spaths_openmp_installed`)
}

destination_names_character <- function(origin_names) {
    .Call(`_spaths_destination_names_character`, origin_names)
}

destination_names_numeric <- function(origin_names) {
    .Call(`_spaths_destination_names_numeric`, origin_names)
}

destination_names_integer <- function(origin_names) {
    .Call(`_spaths_destination_names_integer`, origin_names)
}

destination_names_auto <- function(n_names) {
    .Call(`_spaths_destination_names_auto`, n_names)
}

r_dists_woweights_d <- function(from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2) {
    .Call(`_spaths_r_dists_woweights_d`, from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2)
}

r_dists_woweights_i <- function(from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2) {
    .Call(`_spaths_r_dists_woweights_i`, from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2)
}

r_dists_wweights_d <- function(from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, double_weights, show_progress, bar_limit) {
    .Call(`_spaths_r_dists_wweights_d`, from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, double_weights, show_progress, bar_limit)
}

r_dists_wweights_i <- function(from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, signed_weights, show_progress, bar_limit) {
    .Call(`_spaths_r_dists_wweights_i`, from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, signed_weights, show_progress, bar_limit)
}

r_paths_woweights <- function(from_to, starts_targets, coords, n_cells, early_stopping, haversine, queen, ncores, pairwise, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2) {
    .Call(`_spaths_r_paths_woweights`, from_to, starts_targets, coords, n_cells, early_stopping, haversine, queen, ncores, pairwise, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2)
}

r_paths_wweights <- function(from_to, starts_targets, coords, n_cells, early_stopping, ncores, directed, pairwise, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit) {
    .Call(`_spaths_r_paths_wweights`, from_to, starts_targets, coords, n_cells, early_stopping, ncores, directed, pairwise, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit)
}

r_upd_dists_woweights_d <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2) {
    .Call(`_spaths_r_upd_dists_woweights_d`, from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2)
}

r_upd_dists_woweights_i <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2) {
    .Call(`_spaths_r_upd_dists_woweights_i`, from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2)
}

r_upd_dists_wweights_d <- function(from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, double_weights, show_progress, bar_limit) {
    .Call(`_spaths_r_upd_dists_wweights_d`, from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, double_weights, show_progress, bar_limit)
}

r_upd_dists_wweights_i <- function(from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, signed_weights, show_progress, bar_limit) {
    .Call(`_spaths_r_upd_dists_wweights_i`, from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, signed_weights, show_progress, bar_limit)
}

r_upd_paths_woweights <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, haversine, queen, ncores, pairwise, par_lvl_upd, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2) {
    .Call(`_spaths_r_upd_paths_woweights`, from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, haversine, queen, ncores, pairwise, par_lvl_upd, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2)
}

r_upd_paths_wweights <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit) {
    .Call(`_spaths_r_upd_paths_wweights`, from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit)
}

