# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

from_to_ptr_i <- function(cell_numbers, queen, global, rst_ncol, n_cells, tr_fun_specified, max_neighbors) {
    .Call(`_spaths_from_to_ptr_i`, cell_numbers, queen, global, rst_ncol, n_cells, tr_fun_specified, max_neighbors)
}

from_to_ptr_u <- function(cell_numbers, queen, global, rst_ncol, n_cells, tr_fun_specified, max_neighbors) {
    .Call(`_spaths_from_to_ptr_u`, cell_numbers, queen, global, rst_ncol, n_cells, tr_fun_specified, max_neighbors)
}

openmp_installed <- function() {
    .Call(`_spaths_openmp_installed`)
}

destination_names_character <- function(origin_names) {
    .Call(`_spaths_destination_names_character`, origin_names)
}

destination_names_numeric <- function(origin_names) {
    .Call(`_spaths_destination_names_numeric`, origin_names)
}

destination_names_integer <- function(origin_names) {
    .Call(`_spaths_destination_names_integer`, origin_names)
}

destination_names_auto <- function(n_names) {
    .Call(`_spaths_destination_names_auto`, n_names)
}

r_dists_woweights_d <- function(from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2, from_to_r) {
    .Call(`_spaths_r_dists_woweights_d`, from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2, from_to_r)
}

r_dists_woweights_i <- function(from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2, from_to_r) {
    .Call(`_spaths_r_dists_woweights_i`, from_to, starts_targets, coords, n_cells, haversine, queen, ncores, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2, from_to_r)
}

r_dists_wweights_d <- function(from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, double_weights, show_progress, bar_limit, from_to_r) {
    .Call(`_spaths_r_dists_wweights_d`, from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, double_weights, show_progress, bar_limit, from_to_r)
}

r_dists_wweights_i <- function(from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, signed_weights, show_progress, bar_limit, from_to_r) {
    .Call(`_spaths_r_dists_wweights_i`, from_to, starts_targets, n_cells, early_stopping, ncores, directed, pairwise, int_path, signed_weights, show_progress, bar_limit, from_to_r)
}

r_paths_woweights <- function(from_to, starts_targets, coords, n_cells, early_stopping, haversine, queen, ncores, pairwise, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2, from_to_r) {
    .Call(`_spaths_r_paths_woweights`, from_to, starts_targets, coords, n_cells, early_stopping, haversine, queen, ncores, pairwise, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2, from_to_r)
}

r_paths_wweights <- function(from_to, starts_targets, coords, n_cells, early_stopping, ncores, directed, pairwise, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, from_to_r) {
    .Call(`_spaths_r_paths_wweights`, from_to, starts_targets, coords, n_cells, early_stopping, ncores, directed, pairwise, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, from_to_r)
}

tr_fun_args_d_haversine_queen_i <- function(from_to, row_number, col_number, d_horizontal, d_vertical, d_diagonal, ncores) {
    .Call(`_spaths_tr_fun_args_d_haversine_queen_i`, from_to, row_number, col_number, d_horizontal, d_vertical, d_diagonal, ncores)
}

tr_fun_args_d_haversine_queen_u <- function(from_to, row_number, col_number, d_horizontal, d_vertical, d_diagonal, ncores) {
    .Call(`_spaths_tr_fun_args_d_haversine_queen_u`, from_to, row_number, col_number, d_horizontal, d_vertical, d_diagonal, ncores)
}

tr_fun_args_d_haversine_rook_i <- function(from_to, row_number, d_horizontal, d_vertical, ncores) {
    .Call(`_spaths_tr_fun_args_d_haversine_rook_i`, from_to, row_number, d_horizontal, d_vertical, ncores)
}

tr_fun_args_d_haversine_rook_u <- function(from_to, row_number, d_horizontal, d_vertical, ncores) {
    .Call(`_spaths_tr_fun_args_d_haversine_rook_u`, from_to, row_number, d_horizontal, d_vertical, ncores)
}

tr_fun_args_d_euclidean_queen_i <- function(from_to, row_number, col_number, rst_xres, rst_yres, d_vertical, d_diagonal, ncores) {
    .Call(`_spaths_tr_fun_args_d_euclidean_queen_i`, from_to, row_number, col_number, rst_xres, rst_yres, d_vertical, d_diagonal, ncores)
}

tr_fun_args_d_euclidean_queen_u <- function(from_to, row_number, col_number, rst_xres, rst_yres, d_vertical, d_diagonal, ncores) {
    .Call(`_spaths_tr_fun_args_d_euclidean_queen_u`, from_to, row_number, col_number, rst_xres, rst_yres, d_vertical, d_diagonal, ncores)
}

tr_fun_args_d_euclidean_rook_i <- function(from_to, row_number, rst_xres, rst_yres, ncores) {
    .Call(`_spaths_tr_fun_args_d_euclidean_rook_i`, from_to, row_number, rst_xres, rst_yres, ncores)
}

tr_fun_args_d_euclidean_rook_u <- function(from_to, row_number, rst_xres, rst_yres, ncores) {
    .Call(`_spaths_tr_fun_args_d_euclidean_rook_u`, from_to, row_number, rst_xres, rst_yres, ncores)
}

tr_fun_args_coords_i <- function(from_to, col_row_number, is_from) {
    .Call(`_spaths_tr_fun_args_coords_i`, from_to, col_row_number, is_from)
}

tr_fun_args_coords_u <- function(from_to, col_row_number, is_from) {
    .Call(`_spaths_tr_fun_args_coords_u`, from_to, col_row_number, is_from)
}

tr_fun_args_v_i <- function(from_to, crd, v_vars, v_vars_classes, is_from) {
    .Call(`_spaths_tr_fun_args_v_i`, from_to, crd, v_vars, v_vars_classes, is_from)
}

tr_fun_args_v_u <- function(from_to, crd, v_vars, v_vars_classes, is_from) {
    .Call(`_spaths_tr_fun_args_v_u`, from_to, crd, v_vars, v_vars_classes, is_from)
}

check_weights_i_d <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_i_d`, from_to, weights))
}

check_weights_i_f <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_i_f`, from_to, weights))
}

check_weights_i_i <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_i_i`, from_to, weights))
}

check_weights_i_u <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_i_u`, from_to, weights))
}

check_weights_u_d <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_u_d`, from_to, weights))
}

check_weights_u_f <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_u_f`, from_to, weights))
}

check_weights_u_i <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_u_i`, from_to, weights))
}

check_weights_u_u <- function(from_to, weights) {
    invisible(.Call(`_spaths_check_weights_u_u`, from_to, weights))
}

r_upd_dists_woweights_d <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2, from_to_r) {
    .Call(`_spaths_r_upd_dists_woweights_d`, from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, double_weights, show_progress, bar_limit, radius2, from_to_r)
}

r_upd_dists_woweights_i <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2, from_to_r) {
    .Call(`_spaths_r_upd_dists_woweights_i`, from_to, starts_targets, coords, n_cells, upd_rst_r, haversine, queen, ncores, par_lvl_upd, pairwise, pre, early_stopping, int_path, signed_weights, show_progress, bar_limit, radius2, from_to_r)
}

r_upd_dists_wweights_d <- function(from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, double_weights, show_progress, bar_limit, from_to_r) {
    .Call(`_spaths_r_upd_dists_wweights_d`, from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, double_weights, show_progress, bar_limit, from_to_r)
}

r_upd_dists_wweights_i <- function(from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, signed_weights, show_progress, bar_limit, from_to_r) {
    .Call(`_spaths_r_upd_dists_wweights_i`, from_to, starts_targets, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, signed_weights, show_progress, bar_limit, from_to_r)
}

r_upd_paths_woweights <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, haversine, queen, ncores, pairwise, par_lvl_upd, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2, from_to_r) {
    .Call(`_spaths_r_upd_paths_woweights`, from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, haversine, queen, ncores, pairwise, par_lvl_upd, pre, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, radius2, from_to_r)
}

r_upd_paths_wweights <- function(from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, from_to_r) {
    .Call(`_spaths_r_upd_paths_wweights`, from_to, starts_targets, coords, n_cells, upd_rst_r, early_stopping, ncores, pairwise, directed, par_lvl_upd, int_path, numeric_weights, double_weights, signed_weights, return_dists, show_progress, bar_limit, from_to_r)
}

