# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dists_queen_d <- function(lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2 = 12742020.0) {
    .Call(`_spaths_dists_queen_d`, lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2)
}

dists_rook_d <- function(lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2 = 12742020.0) {
    .Call(`_spaths_dists_rook_d`, lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2)
}

dists_queen_i <- function(lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2 = 12742020.0) {
    .Call(`_spaths_dists_queen_i`, lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2)
}

dists_rook_i <- function(lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2 = 12742020.0) {
    .Call(`_spaths_dists_rook_i`, lat1, lon1, lat2, lon2, yres, xres, nrow, ymin, haversine, ncores, radius2)
}

openmp_installed <- function() {
    .Call(`_spaths_openmp_installed`)
}

